language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t brainstormwilly/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true brainstormwilly/docker-react-test npm run test -- --coverage